version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - apt-get install -y nodejs
      - (cd ottmsc && npm install)
      - (cd ottmsc && npm install -g serverless@1.36.1)
      - sls --version
      - pip3 install virtualenv 
      - mkdir venv
      - (cd ottmsc && mkdir venv && cd venv && virtualenv -p python3 .)
      - find / -name python
      - alias python=python3.6
      - alias python3=python3.6
      - python3 --version
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pwd
      - ls -la
      - cat /codebuild/output/tmp/env.sh
      - cat /codebuild/output/tmp/script.sh
      # - (cd venv/bin && pwd && ls -la && . activate)
      - pip --version
      - pip3 --version
      - python3.6 --version
      - (alias python=python3.6 && cd ottmsc && . ./venv/bin/activate && serverless package --stage staging)
      - (cd ottmsc/_build && ls -la )
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
    # - ottmsc/_build/**/*.zip
    - '**/cloudformation-template-update-stack.json'
    # - location
  name: $(AWS_REGION)-$(date +%Y-%m-%d)
  discard-paths: yes
  #base-directory: location:
#cache:
  #paths:
    # - paths